# Generated by Django 6.1 on 2026-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.IntegerField(unique=True)),
                ('revenue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GeographyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.IntegerField(unique=True)),
                ('usa', models.FloatField()),
                ('usa_pct', models.FloatField()),
                ('china', models.FloatField()),
                ('china_pct', models.FloatField()),
                ('other_countries', models.FloatField()),
                ('other_countries_pct', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('members_millions', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('beverage', models.CharField(max_length=150)),
                ('prep', models.CharField(blank=True, max_length=50)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('total_fat', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('caffeine', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.IntegerField(unique=True)),
                ('beverage', models.FloatField()),
                ('beverage_pct', models.FloatField()),
                ('food', models.FloatField()),
                ('food_pct', models.FloatField()),
                ('other', models.FloatField()),
                ('other_pct', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.IntegerField()),
                ('segment', models.CharField(max_length=30)),
                ('net_revenues', models.FloatField()),
                ('operating_income', models.FloatField(blank=True, null=True)),
                ('operating_margin_pct', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=20)),
                ('open_price', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_pct', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreCountYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.IntegerField(unique=True)),
                ('total', models.IntegerField()),
                ('company_operated', models.IntegerField(blank=True, null=True)),
                ('licensed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=10)),
                ('ownership_type', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('subdivision_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
