# Generated by Django 6.1 on 2026-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentperformance',
            name='admin_costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='depreciation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='product_costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='restructuring',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='store_costs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
